### ISSUE TITLE
pypi package not updated

### ISSUE THREAD

**Issue by khyrulimam** [mitsuhiko/flask-oauth#90]
Hey.. looks like the lib on pypi still on the older version. I've tried to install it on my machine with python3 and got ImportError exception from this line ```from urlparse import urljoin```.

**Comment by zrbecker** [comment]
I was able to fix this by installing it through github
```
pip install git+https://github.com/mitsuhiko/flask-oauth
```
I also had an issue with the oauth2. I had to do 
```
pip uninstall python-oauth2
pip install oauth2
```
It said that it couldn't import oauth2.Client for some reason. All seems to work now though.

**Comment by khyrulimam** [comment]
Yes. I did that as well. But I hope pypi package is up-to-date.
